version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql-spring
    ports:
      - "3306:3306"
    networks:
      - mysql-spring
  adminer :
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - mysql-spring

networks:
  mysql-spring:
    driver: bridge
